name: Publish Docker

inputs:
  dockerhub-username:
    description: 'DockerHub Username'
    required: true
  dockerhub-password:
    description: 'DockerHub Password'
    required: true
  tag:
    description: 'The Docker image Tag for Kestra'
    required: true
  plugins:
    description: 'The Kestra plugins to be used for the build.'
    required: false
  packages:
    description: 'The packages to be installed in the docker image.'
    required: false
    default: ""
  python-libraries:
    description: 'The python libraries to be installed in the docker image.'
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout - Current ref
      uses: actions/checkout@v4

    # Docker setup
    - name: Docker - Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Docker - Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Docker Login
    - name: Docker - Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-password }}

    # Vars
    - name: Docker - Set image name
      shell: bash
      id: vars
      run: |
        TAG=${GITHUB_REF#refs/*/}
        if [[ $TAG = "master" || $TAG == v* ]]; then
          echo "plugins=${{ inputs.plugins }}" >> $GITHUB_OUTPUT
        else
          echo "plugins=--repositories=https://s01.oss.sonatype.org/content/repositories/snapshots ${{ inputs.plugins }}" >> $GITHUB_OUTPUT
        fi

    # Build Docker Image
    - name: Artifacts - Download executable
      uses: actions/download-artifact@v4
      with:
        name: exe
        path: build/executable

    - name: Docker - Copy exe to image
      shell: bash
      run: |
        cp build/executable/* docker/app/kestra && chmod +x docker/app/kestra

    # Docker Build and push
    - name: Docker - Build image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: kestra/kestra:${{ inputs.tag }}
        platforms: linux/amd64,linux/arm64
        build-args: |
          KESTRA_PLUGINS=${{ steps.vars.outputs.plugins }}
          APT_PACKAGES=${{inputs.packages}}
          PYTHON_LIBRARIES=${{inputs.python-libraries}}
