name: Release

on:
  workflow_call:
    inputs:
      docker-tag:
        description: "The Docker image Tag for Kestra"
        type: string
        required: true
      plugins:
        description: "The Kestra plugins to be used for the build."
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        description: "The Dockerhub username."
        required: true
      DOCKERHUB_PASSWORD:
        description: "The Dockerhub password."
        required: true
      SONATYPE_USER:
        description: "The Sonatype username."
        required: true
      SONATYPE_PASSWORD:
        description: "The Sonatype password."
        required: true
      SONATYPE_GPG_KEYID:
        description: "The Sonatype GPG key id."
        required: true
      SONATYPE_GPG_PASSWORD:
        description: "The Sonatype GPG password."
        required: true
      SONATYPE_GPG_FILE:
        description: "The Sonatype GPG file."
        required: true
jobs:
  Docker:
    name: Publish Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
            - tag: ${{inputs.docker-tag}}-no-plugins
              packages: ""
              python-libraries: ""

            - tag: ${{inputs.docker-tag}}
              plugins: ${{inputs.plugins}}
              packages: python3 python3-venv python-is-python3 python3-pip nodejs npm curl zip unzip
              python-libraries: kestra
    steps:
      - uses: actions/checkout@v4
      - name: Publish Docker
        uses: ./.github/actions/publish-docker
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          packages: ${{ matrix.image.packages }}
          plugins: ${{ matrix.image.plugins }}
          python-libraries: ${{ matrix.image.python-libraries }}
          tag: ${{ matrix.image.tag }}

  Maven:
    name: Publish Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Maven
        uses: ./.github/actions/publish-maven
        with:
          sonatype-username: ${{ secrets.SONATYPE_USER }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
          sonatype-gpg-keyid: ${{ secrets.SONATYPE_GPG_KEYID }}
          sonatype-gpg-password: ${{ secrets.SONATYPE_GPG_PASSWORD }}
          sonatype-gpg-file: ${{ secrets.SONATYPE_GPG_FILE }}

  Github:
    name: Github Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - name: Github Release
        uses: ./.github/actions/github-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-personal: ${{ secrets.GH_PERSONAL_TOKEN }}